//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRAKTIKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver_Customer
    {
        public short ID_Driver { get; set; }
        public Nullable<short> ID_Customer { get; set; }
        public Nullable<short> ID_DR_CUS { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
