//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRAKTIKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_buyer
    {
        public short ID_Stock { get; set; }
        public Nullable<short> ID_Buyer { get; set; }
        public Nullable<short> ID_ST_BUY { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
