//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRAKTIKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.Stock_buyer = new HashSet<Stock_buyer>();
        }
    
        public short ID_Stock { get; set; }
        public string Production_name { get; set; }
        public string production_number { get; set; }
        public string Type_STO { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<int> quanity_of_bottles { get; set; }
        public Nullable<int> quanity_of_pallets { get; set; }
        public Nullable<short> production_rows { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_buyer> Stock_buyer { get; set; }
    }
}
